"""create table car, brand and address

Revision ID: b57535b44679
Revises: 4e2380493fb6
Create Date: 2025-08-23 13:30:41.092748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b57535b44679"
down_revision: Union[str, Sequence[str], None] = "4e2380493fb6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("address_brands")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address_brands",
        sa.Column("address_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("brands_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["addresss.id"],
            name=op.f("fk_address_brands_address_id_addresss"),
        ),
        sa.ForeignKeyConstraint(
            ["brands_id"],
            ["brands.id"],
            name=op.f("fk_address_brands_brands_id_brands"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_address_brands")),
        sa.UniqueConstraint(
            "address_id",
            "brands_id",
            name=op.f("idx_unique_address_brands"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
