"""create table car, brand and address

Revision ID: 59912b901092
Revises: b57535b44679
Create Date: 2025-08-23 13:56:40.653520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59912b901092"
down_revision: Union[str, Sequence[str], None] = "b57535b44679"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("addresss", sa.Column("brand_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        op.f("fk_addresss_brand_id_brands"),
        "addresss",
        "brands",
        ["brand_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_addresss_brand_id_brands"), "addresss", type_="foreignkey"
    )
    op.drop_column("addresss", "brand_id")
    # ### end Alembic commands ###
